Разметка страниц в файлах index.html и catalog.html
htmlacademy-htmlcss/1411729-device-1 pull request #2
Opened 2023-09-15 14:53 UTC by AleksanrReva

Выполнил задание 4 из раздела «2.42. Разметка всех страниц»

2023-09-17 16:37 UTC, Kartaviy-arteom requested changes

2023-09-17 16:37 UTC, Kartaviy-arteom commented on catalog.html
> +              <input class="product-search-name" type="text" name="productName" value="Поиск по сайту">
для input нужен label.  атрибуты не нужно писать в стиле camelCase. https://up.htmlacademy.ru/htmlcss-individual/1/criteries#PROJ-02

2023-09-17 16:37 UTC, Kartaviy-arteom commented on catalog.html
> +            <input class="catalog-filter-price" type="range" name="price" min="0" max="9000" step="50" value="5000">
для всех инпутов label

2023-09-17 16:37 UTC, Kartaviy-arteom commented on catalog.html
> +            </ul>
у всей группы чекбоксов одинаковый name, уникальный value. Аналогично радиокнопкам

2023-09-17 16:37 UTC, Kartaviy-arteom commented on catalog.html
> +                <lable class="catalog-filter-name">
lable -  такого элемента нет, label. исправить нужно во всем документе

2023-09-17 16:37 UTC, Kartaviy-arteom commented on catalog.html
> +        </ul>
это две кнопки для сортировки

2023-09-17 16:37 UTC, Kartaviy-arteom commented on catalog.html
> +        <hr class="footer-address-line">
нужно убрать из разметки, будет псевдоэлемент в стилях

2023-09-17 16:37 UTC, Kartaviy-arteom commented on catalog.html
> +      <section class="footer-navigation">
для всех секций нужен заголовок

2023-09-17 16:37 UTC, Kartaviy-arteom commented on index.html
> +        </p>
заголовки нельзя вкладывать в address, в параграф нельзя вкладывать заголовки

2023-09-17 16:37 UTC, Kartaviy-arteom commented on index.html
> +      <h1 class="visually-hidden">Каталог товаров</h1>
это главная страница, у нее главный заголовок не должен быть "каталог товаров"

2023-09-17 16:37 UTC, Kartaviy-arteom commented on index.html
> +            <span class="visually-hidden">&#10094;</span >
здесь должно быть пояснение к кнопке, не символ

2023-09-17 16:37 UTC, Kartaviy-arteom commented on index.html
> +          <button class="product-photo-previos" type="button" value="photoPrevios">
value тут не нужен

2023-09-17 16:37 UTC, Kartaviy-arteom commented on index.html
> +            <input class="services-menu-item" type="radio" name="serviceName" checked>
написание атрибутов

2023-09-17 16:37 UTC, Kartaviy-arteom commented on index.html
> +      </section>
это все одна ссылка

2023-09-17 16:37 UTC, Kartaviy-arteom commented on index.html
> +        <hr class="info-indent-line">
hr не нужен

2023-09-17 16:37 UTC, Kartaviy-arteom commented on index.html
> +        <hr class="info-indent-line">
hr не нужен

2023-09-17 16:37 UTC, Kartaviy-arteom commented on index.html
> +        <form class="subscribe-email-send" action="https://echo.htmlacademy.ru/" method="get">
method="post"

2023-09-17 16:37 UTC, Kartaviy-arteom commented on index.html
> +          <input class="subscribe-email" type="email" name="subscribeEMail" value="Ваш e-mail">
атрибуты наименование

2023-09-19 18:01 UTC, AleksanrReva reviewed
Внёс необходимые правки

2023-09-21 18:40 UTC, Kartaviy-arteom requested changes

2023-09-21 18:40 UTC, Kartaviy-arteom commented on catalog.html
> +                <input class="product-search-name" type="text" name="product-name" value="Поиск по сайту">
поиск по сайту - это placeholder https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/placeholder

2023-09-21 18:40 UTC, Kartaviy-arteom commented on catalog.html
> +        </a>
тут будет картинка

2023-09-21 18:40 UTC, Kartaviy-arteom commented on index.html
> +          <legend class="visually-hidden">Вид услуги</legend>
несколько выглядит непривычно, обчно используют fieldset внутри формы, впринципе можно оставить так

2023-09-21 18:40 UTC, Kartaviy-arteom commented on index.html
> +        </address>
тег address не предназначен для любых почтовых адресов, мы можем его использовать для адреса, если например по этому адресу можем получить услугу. Если это просто какой-то адрес то "p" будет уместен.
Подробнее тут https://html.spec.whatwg.org/multipage/sections.html#the-address-element . Т.е тут ты впринципе можешь его применить, но с ним нужно быть аккуратным

2023-09-21 18:40 UTC, Kartaviy-arteom commented on index.html
> +          .html academy
картинка, это векторный логотип

2023-09-21 18:40 UTC, merged

2023-09-23 06:01 UTC, AleksanrReva commented on index.html
> +          <legend class="visually-hidden">Вид услуги</legend>
и валидатор пропускает. Далее форма не должна понадобиться в этом месте. Если можно оставить, оставляю)